// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrueAccounts.Data;

#nullable disable

namespace TrueAccounts.Migrations
{
    [DbContext(typeof(trueAccountsDbcontext))]
    [Migration("20230112180322_3-addCustomer")]
    partial class _3addCustomer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrueAccounts.Models.Branch", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("branchName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("companyId")
                        .HasColumnType("int");

                    b.Property<string>("contactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("supervisor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("companyId");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("TrueAccounts.Models.Brand", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("brandName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("TrueAccounts.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("TrueAccounts.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("customer_Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("customer_Branch_Id")
                        .HasColumnType("int");

                    b.Property<int>("customer_Current_balance")
                        .HasColumnType("int");

                    b.Property<string>("customer_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customer_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("customer_Opening_balance")
                        .HasColumnType("int");

                    b.Property<int?>("customer_branchid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("customer_branchid");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("TrueAccounts.Models.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("brandId")
                        .HasColumnType("int");

                    b.Property<string>("image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("productName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("purchasePrice")
                        .HasColumnType("int");

                    b.Property<int>("salePrice")
                        .HasColumnType("int");

                    b.Property<string>("unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("brandId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("TrueAccounts.Models.Branch", b =>
                {
                    b.HasOne("TrueAccounts.Models.Company", "company")
                        .WithMany("branches")
                        .HasForeignKey("companyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("company");
                });

            modelBuilder.Entity("TrueAccounts.Models.Customer", b =>
                {
                    b.HasOne("TrueAccounts.Models.Branch", "customer_branch")
                        .WithMany("Customer")
                        .HasForeignKey("customer_branchid");

                    b.Navigation("customer_branch");
                });

            modelBuilder.Entity("TrueAccounts.Models.Product", b =>
                {
                    b.HasOne("TrueAccounts.Models.Brand", "brand")
                        .WithMany("products")
                        .HasForeignKey("brandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("brand");
                });

            modelBuilder.Entity("TrueAccounts.Models.Branch", b =>
                {
                    b.Navigation("Customer");
                });

            modelBuilder.Entity("TrueAccounts.Models.Brand", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("TrueAccounts.Models.Company", b =>
                {
                    b.Navigation("branches");
                });
#pragma warning restore 612, 618
        }
    }
}
